[CI] - Add umami image cron build
TechProber/cloud-estate pull request #3
Opened 2021-11-10 04:30 UTC by yqlbu

### Summary

_Provide an overview..._

### Description

_Add more context to describe the changes_

### Details

- [ ] some project details

### References

- Link #

### Checks

- [ ] Already tested changes in `staging` environment

### Notes

- _Some awesome notes_

2021-11-13 15:38 UTC, kunish requested changes
Maybe it's a better idea that we use the upstream source code directly with cronjob.

Something like this

```yml
jobs:
  build:
     steps:
       - run: |
           git clone https://github.com/mikecao/umami.git
           docker build . -t ghcr.io/techprober/umami
           docker push $_
```

2021-11-13 16:39 UTC, kunish approved these changes
LGTM

2021-11-14 05:25 UTC, yqlbu commented
We should add more details about usage case in `README.md`

2021-11-14 05:28 UTC, yqlbu commented on containers/umami/docker-compose.yaml
> +    image: ghcr.io/techprober/umami:latest
I modified the image name pointing to our `GHCR` registry

2021-11-14 11:03 UTC, yqlbu commented
Already tested in `staging` environment, looks like it is quite stable. Good to proceed to `production`.

2021-11-14 11:05 UTC, kunish approved these changes
LGTM

2021-11-14 11:05 UTC, merged